name: gviz_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - argcomplete=3.6.3
  - aws-c-auth=0.10.1
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.2
  - aws-c-event-stream=0.6.0
  - aws-c-http=0.10.12
  - aws-c-io=0.26.3
  - aws-c-mqtt=0.15.2
  - aws-c-s3=0.11.5
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.10
  - aws-crt-cpp=0.37.4
  - aws-sdk-cpp=1.11.747
  - azure-core-cpp=1.16.2
  - azure-identity-cpp=1.13.3
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.13.0
  - azure-storage-files-datalake-cpp=12.14.0
  - binutils_impl_linux-64=2.45
  - bioconductor-annotationdbi=1.68.0
  - bioconductor-annotationfilter=1.30.0
  - bioconductor-biobase=2.66.0
  - bioconductor-biocfilecache=2.14.0
  - bioconductor-biocgenerics=0.52.0
  - bioconductor-biocio=1.16.0
  - bioconductor-biocparallel=1.40.0
  - bioconductor-biomart=2.62.0
  - bioconductor-biostrings=2.74.0
  - bioconductor-biovizbase=1.54.0
  - bioconductor-bsgenome=1.74.0
  - bioconductor-data-packages=20250625
  - bioconductor-delayedarray=0.32.0
  - bioconductor-ensembldb=2.30.0
  - bioconductor-genomeinfodb=1.42.0
  - bioconductor-genomeinfodbdata=1.2.13
  - bioconductor-genomicalignments=1.42.0
  - bioconductor-genomicfeatures=1.58.0
  - bioconductor-genomicinteractions=1.40.0
  - bioconductor-genomicranges=1.58.0
  - bioconductor-gviz=1.50.0
  - bioconductor-interactionset=1.34.0
  - bioconductor-iranges=2.40.0
  - bioconductor-keggrest=1.46.0
  - bioconductor-matrixgenerics=1.18.0
  - bioconductor-protgenerics=1.38.0
  - bioconductor-rhtslib=3.2.0
  - bioconductor-rsamtools=2.22.0
  - bioconductor-rtracklayer=1.66.0
  - bioconductor-s4arrays=1.6.0
  - bioconductor-s4vectors=0.44.0
  - bioconductor-sparsearray=1.6.0
  - bioconductor-summarizedexperiment=1.36.0
  - bioconductor-ucsc.utils=1.2.0
  - bioconductor-variantannotation=1.52.0
  - bioconductor-xvector=0.46.0
  - bioconductor-zlibbioc=1.52.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - curl=8.19.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc_impl_linux-64=15.2.0
  - gflags=2.2.2
  - gfortran_impl_linux-64=15.2.0
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=15.2.0
  - harfbuzz=12.2.0
  - htslib=1.23
  - icu=75.1
  - jq=1.8.1
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - krb5=1.22.2
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20260107.1
  - libarrow=24.0.0
  - libarrow-acero=24.0.0
  - libarrow-compute=24.0.0
  - libarrow-dataset=24.0.0
  - libarrow-substrait=24.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.19.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libgoogle-cloud=3.3.0
  - libgoogle-cloud-storage=3.3.0
  - libgrpc=1.78.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.26.0
  - libopentelemetry-cpp-headers=1.26.0
  - libparquet=24.0.0
  - libpng=1.6.53
  - libprotobuf=6.33.5
  - libre2-11=2025.11.05
  - libsanitizer=15.2.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.3
  - libuuid=2.41.3
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libzlib=1.3.2
  - lz4-c=1.10.0
  - make=4.4.1
  - ncurses=6.5
  - nlohmann_json=3.12.0
  - oniguruma=6.9.10
  - openssl=3.6.0
  - orc=2.3.0
  - pandoc=3.8.3
  - pango=1.56.4
  - pcre2=10.47
  - pip=25.3
  - pixman=0.46.4
  - prometheus-cpp=1.3.0
  - pthread-stubs=0.4
  - python=3.14.2
  - python_abi=3.14
  - pyyaml=6.0.3
  - r-abind=1.4_8
  - r-arrow=24.0.0
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.1
  - r-base=4.4.3
  - r-base64enc=0.1_6
  - r-bh=1.87.0_1
  - r-bit=4.6.0
  - r-bit64=4.8.2
  - r-bitops=1.0_9
  - r-blob=1.3.0
  - r-bslib=0.11.0
  - r-cachem=1.1.0
  - r-checkmate=2.3.3
  - r-cli=3.6.6
  - r-cluster=2.1.8.2
  - r-codetools=0.2_20
  - r-colorspace=2.1_2
  - r-cpp11=0.5.5
  - r-crayon=1.5.3
  - r-curl=7.1.0
  - r-data.table=1.17.8
  - r-dbi=1.3.0
  - r-dbplyr=2.5.2
  - r-deldir=2.0_4
  - r-dichromat=2.0_0.1
  - r-digest=0.6.39
  - r-dplyr=1.2.1
  - r-ellipsis=0.3.3
  - r-evaluate=1.0.5
  - r-fansi=1.0.7
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-filelock=1.0.3
  - r-fontawesome=0.5.3
  - r-foreign=0.8_91
  - r-formatr=1.14
  - r-formula=1.2_5
  - r-fs=2.1.0
  - r-futile.logger=1.4.9
  - r-futile.options=1.0.1
  - r-generics=0.1.4
  - r-ggplot2=4.0.3
  - r-glue=1.8.1
  - r-gridextra=2.3
  - r-gtable=0.3.6
  - r-highr=0.12
  - r-hmisc=5.2_5
  - r-hms=1.1.4
  - r-htmltable=2.5.0
  - r-htmltools=0.5.9
  - r-htmlwidgets=1.6.4
  - r-httr=1.4.8
  - r-httr2=1.2.2
  - r-igraph=2.1.4
  - r-interp=1.1_6
  - r-isoband=0.3.0
  - r-jpeg=0.1_11
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-knitr=1.51
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-lattice=0.22_9
  - r-latticeextra=0.6_31
  - r-lazyeval=0.2.3
  - r-lifecycle=1.0.5
  - r-magrittr=2.0.5
  - r-mass=7.3_65
  - r-matrix=1.7_5
  - r-matrixstats=1.5.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_4
  - r-mime=0.13
  - r-munsell=0.5.1
  - r-nlme=3.1_169
  - r-nnet=7.3_20
  - r-openssl=2.4.1
  - r-pillar=1.11.1
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-png=0.1_8
  - r-prettyunits=1.2.0
  - r-progress=1.2.3
  - r-purrr=1.2.2
  - r-r6=2.6.1
  - r-rappdirs=0.3.4
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.1_1.1
  - r-rcppeigen=0.3.4.0.2
  - r-rcurl=1.98_1.17
  - r-restfulr=0.0.16
  - r-rjson=0.2.23
  - r-rlang=1.2.0
  - r-rmarkdown=2.31
  - r-rpart=4.1.27
  - r-rsqlite=3.52.0
  - r-rstudioapi=0.18.0
  - r-s7=0.2.2
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-snow=0.4_4
  - r-stringi=1.8.7
  - r-stringr=1.6.0
  - r-survival=3.8_6
  - r-sys=3.4.3
  - r-tibble=3.3.1
  - r-tidyr=1.3.2
  - r-tidyselect=1.2.1
  - r-tinytex=0.59
  - r-utf8=1.2.6
  - r-vctrs=0.7.3
  - r-viridis=0.6.5
  - r-viridislite=0.4.3
  - r-withr=3.0.2
  - r-xfun=0.57
  - r-xml=3.99_0.20
  - r-xml2=1.5.1
  - r-yaml=2.3.12
  - re2=2025.11.05
  - readline=8.3
  - s2n=1.7.3
  - sed=4.9
  - setuptools=80.9.0
  - snappy=1.2.2
  - sysroot_linux-64=2.34
  - tabix=1.11
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomlkit=0.13.3
  - tzdata=2025c
  - xmltodict=1.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - yaml=0.2.5
  - yq=3.4.3
  - zlib=1.3.2
  - zstd=1.5.7