#!/bin/bash
# scp /home/kisa/coding/80K_MPRA/80K-Analysis/06_variant_element_analysis/notebooks/find_valid_gwas_files.sh kisa11_c@172.16.35.182:/data/cephfs-1/scratch/groups/kircher/MPRA/IGVF_Y1_design/projects/80K_MPRA/ludwig_variant_annotations/download_testing
# gwas_join_processor.sh - Script to perform join for one GWAS file

# Slurm directives (adjust as needed for joining)
#SBATCH --job-name=gwas_join_task
#SBATCH --output=slurm_logs/gwas_join_%A_%a.out
#SBATCH --error=slurm_logs/gwas_join_%A_%a.err
#SBATCH --partition=short         # REPLACE with your partition
#SBATCH --time=02:00:00           # Adjust time as needed
#SBATCH --mem=2G                  # Adjust memory as needed (start with 2G, increase if OOM)
#SBATCH --cpus-per-task=1

# Configuration
VALID_FILE_LIST="valid_gwas_files.txt"          # List generated by find_valid_gwas_files.sh
VARIANT_TABLE_FILE="80k_neuro_variant_info_filtered_spdi_tested.tsv" # Your pre-sorted variant table
MERGED_OUTPUT_DIR="merged_gwas_results"        # Directory for merged files

# IMPORTANT: CONFIRM THESE COLUMN INDICES IN YOUR ACTUAL FILES
# Variant table (variant_info_filtered_spdi_tested)
# Assume 'SPDI_elem_chrom' is the 16th column in your_variant_table_sorted.tsv
VARIANT_TABLE_JOIN_KEY_COL=16
VARIANT_TABLE_TOTAL_COLS=$(head -n 1 "$VARIANT_TABLE_FILE" | awk -F'\t' '{print NF}')

# GWAS file (e.g., coffee_consumed_df)
GWAS_JOIN_KEY_COL=1      # 'variant' column
GWAS_MINOR_AF_COL=3      # 'minor_AF'
GWAS_TSTAT_COL=8         # 'tstat'
GWAS_PVAL_COL=10         # 'pval'

# Ensure output directory exists
mkdir -p "$MERGED_OUTPUT_DIR"

TASK_ID=$SLURM_ARRAY_TASK_ID

echo "$(date): Slurm Array Job ID: $SLURM_ARRAY_JOB_ID, Task ID: $TASK_ID - Starting join processing."

# Get the GWAS file path for this task from the list
GWAS_FILE_PATH=$(sed -n "${TASK_ID}p" "$VALID_FILE_LIST")

if [[ -z "$GWAS_FILE_PATH" || ! -f "$GWAS_FILE_PATH" ]]; then
    echo "$(date): Error for Task $TASK_ID: GWAS_FILE_PATH empty or not found: ${GWAS_FILE_PATH}. Exiting." >&2
    exit 1
fi

# Extract just the filename for annotation
# Removes directory path and .tsv.gz extension
SOURCE_GWAS_FILENAME=$(basename "$GWAS_FILE_PATH" .tsv.gz)

# Determine the output filename for the merged result
MERGED_FILENAME="${SOURCE_GWAS_FILENAME}_merged_annotated.tsv.gz"
MERGED_FILEPATH="${MERGED_OUTPUT_DIR}/${MERGED_FILENAME}"

echo "$(date): Task $TASK_ID - Joining ${GWAS_FILE_PATH} with ${VARIANT_TABLE_FILE}"
echo "$(date): Task $TASK_ID - Output will be: ${MERGED_FILEPATH}"

# --- Header Construction ---
# Extract header from the variant table
VARIANT_TABLE_HEADER=$(head -n 1 "$VARIANT_TABLE_FILE")

# Combined header: All from variant table, then selected from GWAS, then the new filename column
COMBINED_HEADER="${VARIANT_TABLE_HEADER}\tminor_AF\ttstat\tpval\tSource_GWAS_File"

# --- Join Operation ---
# File 1: Sorted variant table (excluding header)
# File 2: Gzipped GWAS file (decompressed, excluding header, and sorted)
# The `join` command:
# -t$'\t'       : Use tab as field delimiter
# -1 ${VARIANT_TABLE_JOIN_KEY_COL} : Join on specified column from File 1 (variant table)
# -2 ${GWAS_JOIN_KEY_COL}          : Join on specified column from File 2 (GWAS file)
# -a 1          : Left join - keep all unpairable lines from File 1
# -o ...        : Specify output format.

# Construct the output fields for 'join -o'
# All fields from the variant table (file 1) and then selected fields from the GWAS file (file 2)
OUTPUT_FIELDS="0" # Start with the common join key
for i in $(seq 1 "$VARIANT_TABLE_TOTAL_COLS"); do
    if [[ "$i" -ne "$VARIANT_TABLE_JOIN_KEY_COL" ]]; then # Don't duplicate the join key if it's already there from '0'
        OUTPUT_FIELDS+=" 1.$i"
    fi
done
# Append the selected GWAS columns. Note the order here matches the COMBINED_HEADER.
OUTPUT_FIELDS+=" 2.${GWAS_MINOR_AF_COL} 2.${GWAS_TSTAT_COL} 2.${GWAS_PVAL_COL}"


# Combine header and data, then filter for pval not NA, then add filename, then gzip
# We use 'tail -n +2' to skip headers for the 'join' command
# 'sort -t$'\t' -k${GWAS_JOIN_KEY_COL},${GWAS_JOIN_KEY_COL}' ensures GWAS data is sorted for join.

# Pval column index in the joined output before adding the filename column.
# It will be at VARIANT_TABLE_TOTAL_COLS + 3 (for minor_AF, tstat, pval)
PVAL_COL_IN_JOIN_OUTPUT=$((VARIANT_TABLE_TOTAL_COLS + 3))

if (echo -e "$COMBINED_HEADER"; \
    join -t$'\t' -1 "$VARIANT_TABLE_JOIN_KEY_COL" -2 "$GWAS_JOIN_KEY_COL" -a 1 -o "$OUTPUT_FIELDS" \
         <(tail -n +2 "$VARIANT_TABLE_FILE" | sort -t$'\t' -k"$VARIANT_TABLE_JOIN_KEY_COL","$VARIANT_TABLE_JOIN_KEY_COL") \
         <(zcat "$GWAS_FILE_PATH" | tail -n +2 | sort -t$'\t' -k"$GWAS_JOIN_KEY_COL","$GWAS_JOIN_KEY_COL") \
    ) | awk -F'\t' -v pval_col_idx="$PVAL_COL_IN_JOIN_OUTPUT" -v filename_col_val="$SOURCE_GWAS_FILENAME" '
    BEGIN { OFS="\t" }
    NR==1 { print; next } # Print header (already constructed)
    # Filter for pval not "NaN" and not empty, then append the filename
    $pval_col_idx != "NaN" && $pval_col_idx != "" { print $0, filename_col_val }
    ' | gzip > "$MERGED_FILEPATH" ; then
    echo "$(date): Task $TASK_ID - Successfully merged, filtered, and annotated: ${MERGED_FILEPATH}"
else
    echo "$(date): Error for Task $TASK_ID: Failed to join/filter/annotate ${GWAS_FILE_PATH}. Removing partial file." >&2
    rm -f "$MERGED_FILEPATH"
    exit 1
fi

echo "$(date): Task $TASK_ID finished."
exit 0