suppressPackageStartupMessages({
  library(Gviz)
  library(GenomicInteractions)
  library(GenomicRanges)
  library(rtracklayer)
  library(data.table)
  library(arrow)
  library(biomaRt)
})

# BiocFileCache dplyr compat patch
local({
  new_fn <- function(bfc) {
    tryCatch({
      info <- BiocFileCache:::.sql_connect_RO(BiocFileCache:::.sql_dbfile(bfc))
      con  <- info$con
      src  <- dbplyr::src_dbi(con)
      tbl  <- dplyr::tbl(src, "metadata") |> dplyr::collect()
    }, finally = { BiocFileCache:::.sql_disconnect(info) })
    tbl$value[tbl$key == "schema_version"]
  }
  assignInNamespace(".sql_schema_version", new_fn, ns = "BiocFileCache")
})

# ── Configuration ──────────────────────────────────────────────────────────────
DATA_BASE_DIR <- "/home/kisa/coding"

ATAC_FILE    <- file.path(DATA_BASE_DIR, "80K_MPRA/WTC11_ATAC_Ahituv/DIV14_WTC11-NGN2_ExN_ATAC-seq.idr0.05.bfilt.narrowPeak")
REGION_FILE  <- file.path(DATA_BASE_DIR, "80K_MPRA/WTC11_ATAC_Ahituv/80K_MPRA_all_sequence_regions.bed")
EMS_DIR      <- file.path(DATA_BASE_DIR, "80K_MPRA/eQTL_fine-mapped/EMS_public")
MPRA_FILE    <- file.path(DATA_BASE_DIR, "80K_MPRA/80K-Analysis/09_mpra_manuscript/data/variant_effects/2603_NGN2_variants_with_model_predictions_cadd16_cadd17_alphaGenome_encoder.tsv.gz")

# Preprocessed eQTL files (generated by src/preprocess_eqtl_data.py)
GTEX_PROC    <- "data/eqtl/gtex_processed.tsv.gz"
META_PROC    <- "data/eqtl/metabrain_processed.tsv.gz"
EMS_ARCS     <- "data/eqtl/ems_arcs_processed.tsv.gz"

OUTPUT_DIR   <- "figures"

# ── Brain ATAC-seq bigwig files (GSE113480, local) ─────────────────────────────
BRAIN_ATAC_BW <- list(
  astrocyte   = "data/atac_peaks/GSE113480_astrocyte.atac-seq.bigwig",
  cortical    = "data/atac_peaks/GSE113480_cortical.atac-seq.bigwig",
  hippocampus = "data/atac_peaks/GSE113480_hippocampal.atac-seq.bigwig",
  motor       = "data/atac_peaks/GSE113480_motor.atac-seq.bigwig"
)

BRAIN_ATAC_COLS <- c(
  astrocyte   = "#E8A838",   # warm amber
  cortical    = "#4A90D9",   # blue
  hippocampus = "#5BAD5B",   # green
  motor       = "#A855A8"    # purple
)

# ── SCREEN cCRE files ──────────────────────────────────────────────────────────
CCRE_ALL_FILE   <- "/home/kisa/coding/80K_MPRA/cCREs_overlap/newest_screen/GRCh38-cCREs_screen_v4.bed"
CCRE_BRAIN_FILE <- "/home/kisa/coding/80K_MPRA/cCREs_overlap/SCREEN_tissue/enrichment_over_tissues/brain_cCRE_open_filtered.bed.gz"

# ── Color scheme ───────────────────────────────────────────────────────────────
COL_GRAY        <- "#CCCCCC"
COL_BRAIN_LIGHT <- "#7EB8D9"
COL_BRAIN_DARK  <- "#1B6CA8"
COL_BRAIN_NEG   <- "#D45E1A"    # warm orange: brain negative-beta arc in color_only mode
COL_NONBR_LIGHT <- "#AAAAAA"
COL_BLACK       <- "#222222"
COL_HIGHLIGHT   <- "#e31a1c"    # variant-of-interest marker

COL_REGION_TESTED  <- "#888888"
COL_REGION_SIG     <- "#A6D1F2"
COL_VAR_TESTED     <- "#333333"
COL_VAR_SIG_UP     <- "#2ca02c"
COL_VAR_SIG_DOWN   <- "#ff7f0e"
COL_VAR_HIGHLIGHT  <- "#e31a1c"

# NC accession → UCSC chromosome (GRCh38)
NC_TO_UCSC <- c(
  "NC_000001.11"="chr1",  "NC_000002.12"="chr2",  "NC_000003.12"="chr3",
  "NC_000004.12"="chr4",  "NC_000005.10"="chr5",  "NC_000006.12"="chr6",
  "NC_000007.14"="chr7",  "NC_000008.11"="chr8",  "NC_000009.12"="chr9",
  "NC_000010.11"="chr10", "NC_000011.10"="chr11", "NC_000012.12"="chr12",
  "NC_000013.11"="chr13", "NC_000014.9"="chr14",  "NC_000015.10"="chr15",
  "NC_000016.10"="chr16", "NC_000017.11"="chr17", "NC_000018.10"="chr18",
  "NC_000019.10"="chr19", "NC_000020.11"="chr20", "NC_000021.9"="chr21",
  "NC_000022.11"="chr22", "NC_000023.11"="chrX",  "NC_000024.10"="chrY"
)

# ── Helpers ─────────────────────────────────────────────────────────────────────

# Map abs(beta) in [0, 1+] to a color on a gradient.
# n_bins discrete levels for tractable track counts.
beta_to_color <- function(abs_beta, is_brain, is_sig, n_bins = 5L) {
  if (!is_sig) return(COL_GRAY)
  t    <- pmin(abs_beta / 1.0, 1.0)
  bin  <- max(1L, ceiling(t * n_bins))
  if (is_brain) {
    colorRampPalette(c(COL_BRAIN_LIGHT, COL_BRAIN_DARK))(n_bins)[bin]
  } else {
    colorRampPalette(c(COL_NONBR_LIGHT, COL_BLACK))(n_bins)[bin]
  }
}

# Map abs(beta) to color for negative arcs in color_only mode (warm palette).
beta_to_color_neg <- function(abs_beta, is_brain, is_sig, n_bins = 5L) {
  if (!is_sig) return(COL_GRAY)
  t    <- pmin(abs_beta / 1.0, 1.0)
  bin  <- max(1L, ceiling(t * n_bins))
  if (is_brain) {
    colorRampPalette(c("#F5C6A0", COL_BRAIN_NEG))(n_bins)[bin]
  } else {
    colorRampPalette(c("#CCAA88", "#8B4513"))(n_bins)[bin]
  }
}

# Map -log10(p) to a discrete lwd bin (3 levels). NA → thin line.
pval_to_lwd <- function(p_val) {
  p_val <- replace(p_val, is.na(p_val), 1)
  log_p <- -log10(pmax(p_val, 1e-300))
  ifelse(log_p > 3, 2.5, ifelse(log_p > 1.3, 1.5, 0.8))
}

# Map PIP (fine-mapping posterior) to lwd — used for GTEx which has no p-value.
pip_to_lwd <- function(pip) {
  pip <- replace(pip, is.na(pip), 0)
  ifelse(pip > 0.5, 2.5, ifelse(pip > 0.1, 1.5, 0.8))
}

# ── Data loaders ─────────────────────────────────────────────────────────────────

load_mpra <- function(chrom, from, to) {
  chrom_num <- sub("^chr", "", chrom)
  tryCatch({
    dt <- fread(
      cmd       = sprintf("zcat '%s'", MPRA_FILE),
      select    = c(2L, 5L, 16L, 17L, 19L, 25L, 26L, 64L, 65L),
      col.names = c("chr_pos_ref_alt", "pos0", "padj", "logFC",
                    "is_sig", "ref_activity", "ref_sig", "alt_activity", "alt_sig")
    )
    dt <- dt[grepl(paste0("^", chrom_num, "-"), chr_pos_ref_alt)]
    dt <- dt[pos0 >= from & pos0 <= to]
    if (nrow(dt) == 0L) return(NULL)
    as_bool <- function(x) x == "True" | x == TRUE
    dt[, is_sig  := as_bool(is_sig)]
    dt[, ref_sig := as_bool(ref_sig)]
    dt[, alt_sig := as_bool(alt_sig)]
    dt[, chrom   := chrom]
    dt
  }, error = function(e) { message("MPRA load error: ", e$message); NULL })
}

load_mpra_regions <- function(chrom, from, to) {
  tryCatch({
    dt <- fread(
      cmd = sprintf(
        "awk -v c='%s' -v f=%d -v t=%d '$1==c && $3>=f && $2<=t' '%s'",
        chrom, from, to, REGION_FILE
      ),
      col.names = c("chr", "start", "end", "name", "strand", "score"),
      sep       = "\t"
    )
    if (nrow(dt) == 0L) return(NULL)
    dt
  }, error = function(e) { message("Region load error: ", e$message); NULL })
}

load_atac <- function(chrom, from, to) {
  tryCatch({
    dt <- fread(
      cmd = sprintf(
        "awk -v c='%s' -v f=%d -v t=%d '$1==c && $3>=f && $2<=t' '%s'",
        chrom, from, to, ATAC_FILE
      ),
      col.names = c("chr","start","end","name","score","strand",
                    "signalValue","pValue","qValue","peak")
    )
    if (nrow(dt) == 0L) return(NULL)
    dt
  }, error = function(e) { message("ATAC load error: ", e$message); NULL })
}

load_screen_ccres <- function(chrom, from, to) {
  tryCatch({
    all_dt <- fread(
      cmd = sprintf(
        "awk -v c='%s' -v f=%d -v t=%d '$1==c && $3>=f && $2<=t' '%s'",
        chrom, from, to, CCRE_ALL_FILE
      ),
      col.names = c("chr", "start", "end", "element_id", "accession", "type"),
      sep = "\t"
    )
    if (nrow(all_dt) == 0L) return(NULL)

    brain_dt <- fread(
      cmd = sprintf(
        "zcat '%s' | awk -v c='%s' -v f=%d -v t=%d '$1==c && $3>=f && $2<=t'",
        CCRE_BRAIN_FILE, chrom, from, to
      ),
      col.names = c("chr", "start", "end", "accession", "score", "strand",
                    "thick_start", "thick_end", "rgb", "type2", "tissue"),
      sep = "\t",
      fill = TRUE
    )

    all_dt[, is_brain := accession %in% brain_dt$accession]
    all_dt
  }, error = function(e) { message("cCRE load error: ", e$message); NULL })
}

#' Load preprocessed GTEx eQTLs at the exact variant position.
#' Only arcs whose variant anchor matches pos are returned.
#' v_start in the file is already 0-based; pos argument is also 0-based.
load_gtex <- function(chrom, pos) {
  if (!file.exists(GTEX_PROC)) {
    message("GTEx preprocessed file not found. Run: python src/preprocess_eqtl_data.py")
    return(NULL)
  }
  tryCatch({
    dt <- fread(
      cmd = sprintf(
        "zcat '%s' | awk -v c='%s' -v p=%d 'NR==1 || ($1==c && $2==p)'",
        GTEX_PROC, chrom, pos
      ),
      sep = "\t"
    )
    if (nrow(dt) == 0L) return(NULL)
    # is_brain comes from Python as "True"/"False" strings
    dt[, is_brain := is_brain %in% c("True", "TRUE", TRUE)]
    dt
  }, error = function(e) { message("GTEx load error: ", e$message); NULL })
}

#' Load preprocessed Metabrain eQTLs at the exact variant position.
#' metabrain_dedup: "all_sig" (default), "cortex_EUR", or "best_pvalue"
load_metabrain <- function(chrom, pos, metabrain_dedup = "all_sig") {
  if (!file.exists(META_PROC)) {
    message("Metabrain preprocessed file not found. Run: python src/preprocess_eqtl_data.py")
    return(NULL)
  }
  tryCatch({
    dt <- fread(
      cmd = sprintf(
        "zcat '%s' | awk -v c='%s' -v p=%d 'NR==1 || ($1==c && $13==p)'",
        META_PROC, chrom, pos
      ),
      sep = "\t"
    )
    if (nrow(dt) == 0L) return(NULL)

    # Convert Python "True"/"False" strings to R logical
    as_lgl <- function(x) x %in% c("True", "TRUE", TRUE)
    dt[, is_sig         := as_lgl(is_sig)]
    dt[, is_cortex_EUR  := as_lgl(is_cortex_EUR)]
    dt[, is_best_pvalue := as_lgl(is_best_pvalue)]

    # Apply dedup mode filter
    if (metabrain_dedup == "cortex_EUR") {
      dt <- dt[is_cortex_EUR == TRUE]
    } else if (metabrain_dedup == "best_pvalue") {
      dt <- dt[is_best_pvalue == TRUE]
    }
    # "all_sig": no tissue filter — keep all rows; significance filtered downstream
    if (nrow(dt) == 0L) return(NULL)
    dt
  }, error = function(e) { message("Metabrain load error: ", e$message); NULL })
}

#' Load preprocessed EMS arc data at the exact variant position.
#' Returns arc-format data compatible with build_eqtl_arc_tracks().
#' pip = ems (calibrated causal prob); beta = ems_normalized; is_sig = ems > 0.001.
load_ems_arcs <- function(chrom, pos) {
  if (!file.exists(EMS_ARCS)) {
    message("EMS arcs file not found. Run: python src/preprocess_ems_data.py")
    return(NULL)
  }
  tryCatch({
    dt <- fread(
      cmd = sprintf(
        "zcat '%s' | awk -v c='%s' -v p=%d 'NR==1 || ($1==c && $2==p)'",
        EMS_ARCS, chrom, pos
      ),
      sep = "\t"
    )
    if (nrow(dt) == 0L) return(NULL)
    dt[, is_brain := is_brain %in% c("True", "TRUE", TRUE)]
    dt[, is_sig   := is_sig   %in% c("True", "TRUE", TRUE)]
    dt
  }, error = function(e) { message("EMS arcs load error: ", e$message); NULL })
}

load_ems <- function(chrom, from, to) {
  files <- list.files(EMS_DIR, pattern = "\\.tsv\\.bgz$", full.names = TRUE)
  files <- files[!grepl("Zone.Identifier", files, fixed = TRUE)]

  load_one <- function(f) {
    tryCatch({
      cmd <- sprintf(
        "bgzip -d -c '%s' | awk -v chr='%s' -v f=%d -v t=%d 'NR==1{next} {split($1,a,\"_\"); if(a[1]==chr && int(a[2])>=f && int(a[2])<=t) print}'",
        f, chrom, from, to
      )
      dt <- fread(cmd = cmd,
                  col.names = c("v","g","rf_score_raw","ems","ems_normalized"))
      if (nrow(dt) == 0L) return(NULL)
      tissue       <- sub("\\.tsv\\.bgz$", "", sub("ems_top_", "", basename(f)))
      dt[, tissue   := tissue]
      dt[, is_brain := startsWith(tissue, "Brain_")]
      dt[, pos0     := as.integer(sub(paste0("^", chrom, "_([0-9]+)_.*"), "\\1", v))]
      dt
    }, error = function(e) NULL)
  }

  rows <- Filter(Negate(is.null), lapply(files, load_one))
  if (length(rows) == 0L) return(NULL)
  rbindlist(rows)
}

# ── Track builders ────────────────────────────────────────────────────────────

build_mpra_region_track <- function(regions_dt, mpra_dt, genome, chrom,
                                    col_tested = COL_REGION_TESTED,
                                    col_sig    = COL_REGION_SIG) {
  regions_dt <- copy(regions_dt)
  s  <- as.integer(regions_dt$start)
  e  <- as.integer(regions_dt$end)
  ok <- !is.na(s) & !is.na(e)
  if (!all(ok)) {
    regions_dt <- regions_dt[ok]; s <- s[ok]; e <- e[ok]
  }
  if (nrow(regions_dt) == 0L) return(NULL)
  regions_dt[, is_sig_region := FALSE]
  if (!is.null(mpra_dt)) {
    sig_pos <- as.integer(mpra_dt[(ref_sig) | (alt_sig), pos0])
    if (length(sig_pos) > 0L) {
      region_gr <- GRanges(regions_dt$chr, IRanges(s, e))
      sig_gr    <- GRanges(chrom, IRanges(sig_pos, sig_pos + 1L))
      hits      <- findOverlaps(region_gr, sig_gr)
      regions_dt[queryHits(hits), is_sig_region := TRUE]
    }
  }
  fills <- ifelse(regions_dt$is_sig_region, col_sig, col_tested)
  gr    <- GRanges(regions_dt$chr, IRanges(s, e))
  AnnotationTrack(gr, genome = genome, name = "MPRA\nRegions",
                  fill = fills, col = NA, stacking = "dense",
                  background.title = "white", col.title = "black")
}

build_mpra_variant_track <- function(dt, chrom, genome, target_pos,
                                     col_tested    = COL_VAR_TESTED,
                                     col_sig_up    = COL_VAR_SIG_UP,
                                     col_sig_down  = COL_VAR_SIG_DOWN,
                                     col_highlight = COL_VAR_HIGHLIGHT) {
  fills   <- rep(col_tested, nrow(dt))
  borders <- rep(NA_character_, nrow(dt))
  fills[dt$is_sig & dt$logFC > 0]  <- col_sig_up
  fills[dt$is_sig & dt$logFC < 0]  <- col_sig_down
  target_idx <- which(dt$pos0 == target_pos)
  if (length(target_idx) > 0L) borders[target_idx] <- col_highlight
  p  <- as.integer(dt$pos0)
  gr <- GRanges(chrom, IRanges(p, p + 1L))
  AnnotationTrack(gr, genome = genome, name = "MPRA\nVariants",
                  fill = fills, col = borders, stacking = "dense",
                  background.title = "white", col.title = "black")
}

# ATAC: filled rectangles spanning full peak width, color-coded by signalValue.
build_atac_track <- function(dt, genome, chrom) {
  sv      <- dt$signalValue
  sv_norm <- (sv - min(sv)) / max(max(sv) - min(sv), 0.001)
  pal     <- colorRampPalette(c(COL_BRAIN_LIGHT, COL_BRAIN_DARK))(100L)
  fills   <- pal[pmax(1L, round(sv_norm * 99) + 1L)]

  # narrowPeak is 0-based: add 1 to start for GRanges (1-based)
  gr <- GRanges(dt$chr, IRanges(dt$start + 1L, dt$end))

  AnnotationTrack(
    gr, genome = genome, name = "NGN2\nATAC",
    fill = fills, col = NA,
    stacking = "dense",
    background.title = "white", col.title = "black"
  )
}

build_ccre_track <- function(dt, genome, chrom,
                             col_brain = COL_BRAIN_DARK,
                             col_other = COL_GRAY) {
  fills <- ifelse(dt$is_brain, col_brain, col_other)
  # BED is 0-based; GRanges is 1-based
  gr <- GRanges(chrom, IRanges(dt$start + 1L, dt$end))
  AnnotationTrack(
    gr,
    genome   = genome,
    name     = "SCREEN\ncCREs",
    fill     = fills,
    col      = NA,
    stacking = "dense",
    background.title = "white",
    col.title        = "black"
  )
}

#' Load a local bigwig over [from, to] and return a Gviz DataTrack.
build_brain_atac_bw_track <- function(bw_path, name, chrom, from, to,
                                       col = COL_BRAIN_DARK, genome = "hg38") {
  if (!file.exists(bw_path)) {
    message("[WARN] BigWig not found: ", bw_path); return(NULL)
  }
  tryCatch({
    gr <- GRanges(chrom, IRanges(from, to))
    bw <- rtracklayer::import.bw(bw_path, which = gr)
    if (length(bw) == 0L) return(NULL)
    DataTrack(
      range            = bw,
      data             = bw$score,
      type             = "histogram",
      genome           = genome,
      name             = name,
      col.histogram    = col,
      fill.histogram   = col,
      background.title = "white",
      col.title        = "black"
    )
  }, error = function(e) {
    message("[WARN] BigWig load failed (", name, "): ", e$message); NULL
  })
}

#' Build DataTracks for a subset of BRAIN_ATAC_BW entries.
#' @param which  Character vector of ids — any subset of names(BRAIN_ATAC_BW).
build_brain_atac_tracks <- function(chrom, from, to,
                                     which  = names(BRAIN_ATAC_BW),
                                     genome = "hg38") {
  Filter(Negate(is.null), lapply(which, function(id) {
    bw_path <- BRAIN_ATAC_BW[[id]]
    if (is.null(bw_path)) {
      message("[WARN] Unknown brain ATAC id: ", id); return(NULL)
    }
    col <- if (!is.na(BRAIN_ATAC_COLS[id])) BRAIN_ATAC_COLS[[id]] else COL_BRAIN_DARK
    build_brain_atac_bw_track(bw_path, id, chrom, from, to,
                               col = col, genome = genome)
  }))
}

#' Build one InteractionTrack for a single (color, lwd) group.
make_interaction_track <- function(sub_df, col, lwd_val, name, chrom, genome) {
  if (nrow(sub_df) == 0L) return(NULL)
  gi <- GenomicInteractions(
    GRanges(sub_df[["v_chr"]], IRanges(as.integer(sub_df[["v_start"]]) + 1L,
                                       as.integer(sub_df[["v_end"]]))),
    GRanges(sub_df[["g_chr"]], IRanges(as.integer(sub_df[["g_start"]]) + 1L,
                                       as.integer(sub_df[["g_end"]])))
  )
  if (length(gi) == 0L) return(NULL)
  tr <- InteractionTrack(gi, name = name, chromosome = chrom)
  displayPars(tr) <- list(
    col.interactions      = col,
    col.outside           = col,
    col.anchors.fill      = "white",
    col.anchors.line      = "white",
    interaction.dimension = "height",
    anchor.height         = 0,
    lwd.interactions      = lwd_val,
    showFeatureId         = FALSE,
    showAnchors           = FALSE,
    background.title      = "white",
    col.title             = "black"
  )
  tr
}

#' Build eQTL arc tracks from a pre-filtered data frame.
#'
#' df must have columns: v_chr, v_start, v_end, g_chr, g_start, g_end,
#'                        beta, p_val, is_sig, is_brain
#'
#' arc_mode:
#'   "split_panel" — returns named list: $positive (tracks), $negative (tracks)
#'   "color_only"  — returns list of all tracks (positive = blue, negative = warm)
build_eqtl_arc_tracks <- function(df, name, genome, chrom,
                                   arc_mode   = "split_panel",
                                   n_bins     = 5L,
                                   arc_lwd    = 2.5) {
  if (is.null(df) || nrow(df) == 0L) return(list())

  df <- as.data.frame(df)

  # Keep only significant arcs
  df <- df[df$is_sig, , drop = FALSE]
  if (nrow(df) == 0L) return(list())

  df$abs_beta <- abs(df$beta)
  df$is_pos   <- df$beta >= 0

  # 2-class color: brain = blue, non-brain = gray
  df$color   <- ifelse(df$is_brain, COL_BRAIN_DARK, "#888888")
  df$lwd_val <- arc_lwd

  # One track per color class (2 tracks max per source)
  df$track_key <- df$color

  build_group <- function(sub, label) {
    Filter(Negate(is.null), lapply(unique(sub$track_key), function(k) {
      rows <- sub[sub$track_key == k, , drop = FALSE]
      make_interaction_track(rows, rows$color[1L], rows$lwd_val[1L],
                             label, chrom, genome)
    }))
  }

  if (arc_mode == "split_panel") {
    pos_df <- df[df$is_pos, , drop = FALSE]
    neg_df <- df[!df$is_pos, , drop = FALSE]
    list(
      positive = build_group(pos_df, paste0(name, "\n(+beta)")),
      negative = build_group(neg_df, paste0(name, "\n(-beta)"))
    )
  } else {
    # color_only: one flat list of tracks
    build_group(df, name)
  }
}

build_ems_track <- function(dt, genome, chrom) {
  dt[, is_sig := rf_score_raw > 0.5]
  dt[, color  := mapply(beta_to_color, 0.5, is_brain, is_sig)]  # fixed beta for EMS

  max_score <- max(dt$ems_normalized, na.rm = TRUE)
  ylim_val  <- c(0, max_score * 1.05)

  groups    <- split(dt, dt$color)
  subtracks <- lapply(names(groups), function(col) {
    g  <- groups[[col]]
    g  <- g[, .(ems_normalized = max(ems_normalized, na.rm = TRUE)), by = pos0]
    gr <- GRanges(chrom, IRanges(g$pos0, g$pos0 + 1L))
    DataTrack(range = gr, data = g$ems_normalized,
              type = "h", genome = genome, name = "EMS",
              col = col, col.histogram = col, fill.histogram = col,
              ylim = ylim_val, background.title = "white", col.title = "black")
  })

  if (length(subtracks) == 1L) return(subtracks[[1L]])
  OverlayTrack(trackList = subtracks, name = "EMS")
}

build_gene_track <- function(chrom, from, to, genome) {
  chrom_num <- sub("^chr", "", chrom)
  mirrors   <- c("https://www.ensembl.org", "https://useast.ensembl.org",
                 "https://asia.ensembl.org")

  for (host in mirrors) {
    track <- tryCatch({
      ensembl <- biomaRt::useMart(
        "ENSEMBL_MART_ENSEMBL", dataset = "hsapiens_gene_ensembl",
        host = host
      )
      # transcript_is_canonical is reliable as an attribute but not as a BioMart filter;
      # fetch IDs first, filter in R, then pass as ensembl_transcript_id filter.
      canon_tbl <- biomaRt::getBM(
        attributes = c("ensembl_transcript_id", "transcript_is_canonical"),
        filters    = "chromosomal_region",
        values     = list(paste0(chrom_num, ":", from, ":", to)),
        mart       = ensembl
      )
      canon_ids <- canon_tbl$ensembl_transcript_id[
        !is.na(canon_tbl$transcript_is_canonical) & canon_tbl$transcript_is_canonical == 1
      ]
      tr_filter <- if (length(canon_ids) > 0L)
        list(ensembl_transcript_id = canon_ids) else list()

      BiomartGeneRegionTrack(
        genome               = genome,
        chromosome           = chrom,
        start                = from,
        end                  = to,
        name                 = "Genes",
        biomart              = ensembl,
        transcriptAnnotation = "symbol",
        filter               = tr_filter,
        col.line             = "#444444",
        fill                 = "#444444",
        col                  = "#444444",
        background.title     = "white",
        col.title            = "black"
      )
    }, error = function(e) {
      message("  Gene track mirror failed (", host, "): ", e$message); NULL
    })
    if (!is.null(track)) return(track)
  }

  message("Gene track unavailable (BioMart): all mirrors failed.")
  NULL
}

# ── rsID resolver ──────────────────────────────────────────────────────────────

# Try Ensembl REST API — separate infrastructure from BioMart, usually more reliable.
.resolve_via_ensembl_rest <- function(rsid) {
  url <- paste0("https://rest.ensembl.org/variation/human/",
                rsid, "?content-type=application/json")
  tryCatch({
    resp <- httr::GET(url, httr::timeout(15))
    if (httr::status_code(resp) != 200L) return(NULL)
    data <- httr::content(resp, as = "parsed")
    for (m in data$mappings) {
      if (!identical(m$assembly_name, "GRCh38")) next
      # location format: "15:67064084-67064084"
      parts      <- strsplit(m$location, "[:-]")[[1L]]
      chrom      <- paste0("chr", parts[1L])
      pos_0based <- as.integer(parts[2L]) - 1L
      alleles    <- strsplit(m$allele_string, "/")[[1L]]
      if (length(alleles) < 2L) next
      return(list(chrom = chrom, pos = pos_0based,
                  ref = alleles[1L], alt = alleles[2L]))
    }
    NULL
  }, error = function(e) NULL)
}

resolve_rsid <- function(rsid) {
  message("  Resolving ", rsid, " ...")

  # Try 1: Ensembl REST API (no SOAP overhead, different backend)
  message("    Trying Ensembl REST API...")
  coords <- .resolve_via_ensembl_rest(rsid)
  if (!is.null(coords)) {
    message("  Resolved via REST: ", coords$chrom, ":", coords$pos,
            " (0-based) | alleles: ", coords$ref, ">", coords$alt)
    return(coords)
  }

  # Try 2: BioMart SOAP mirrors
  message("    REST failed — trying BioMart mirrors...")
  mirrors <- c("https://www.ensembl.org", "https://useast.ensembl.org",
               "https://asia.ensembl.org")
  for (host in mirrors) {
    mart <- tryCatch(
      biomaRt::useMart("ENSEMBL_MART_SNP", dataset = "hsapiens_snp", host = host),
      error = function(e) NULL
    )
    if (is.null(mart)) next
    res <- tryCatch(
      biomaRt::getBM(
        attributes = c("refsnp_id", "chr_name", "chrom_start", "allele"),
        filters    = "snp_filter",
        values     = rsid,
        mart       = mart
      ),
      error = function(e) NULL
    )
    if (is.null(res) || nrow(res) == 0L) next
    row        <- res[1L, ]
    chrom      <- paste0("chr", row$chr_name)
    pos_0based <- as.integer(row$chrom_start) - 1L
    alleles    <- strsplit(as.character(row$allele), "/")[[1L]]
    ref        <- alleles[1L]
    alt        <- if (length(alleles) > 1L) alleles[2L] else NA_character_
    message("  Resolved via BioMart (", host, "): ", chrom, ":", pos_0based,
            " (0-based) | alleles: ", ref, ">", alt)
    return(list(chrom = chrom, pos = pos_0based, ref = ref, alt = alt))
  }

  stop("Could not resolve ", rsid, " via Ensembl REST or BioMart. ",
       "Pass chrom/pos/ref/alt directly instead.")
}

# ── UCSC / external bigwig ATAC track builder ─────────────────────────────────
#' Build Gviz DataTracks from bigwig sources, hub URLs, or catalog ids.
#' Requires ucsc_atac_explorer.R to be sourced (auto-sourced if not yet loaded).
#'
#' @param ucsc_atac  Character vector of any mix of:
#'   - UCSC browser URLs containing hubUrl= (all bigwigs in that hub for the region)
#'   - Track hub .txt URLs (e.g. "https://ggoma.s3.amazonaws.com/hub_basic.txt")
#'   - Direct bigwig URLs (https://, file://, or absolute path ending in .bw/.bigwig)
#'   - Catalog ids from ATAC_HUB_CATALOG$id (e.g. "boca_glut_dlPFC")
#'   Named elements use the name as the track label (only applies to single-track entries).
build_ucsc_atac_tracks <- function(ucsc_atac, chrom, from, to) {
  .ensure_explorer <- function() {
    if (!exists("build_bw_track", mode = "function")) {
      explorer <- file.path("src", "ucsc_atac_explorer.R")
      if (file.exists(explorer)) source(explorer)
      else message("[WARN] ucsc_atac_explorer.R not found — source it manually")
    }
  }

  tracks_out <- list()
  for (i in seq_along(ucsc_atac)) {
    entry <- ucsc_atac[[i]]
    label <- if (!is.null(names(ucsc_atac)) && nchar(names(ucsc_atac)[i]) > 0)
               names(ucsc_atac)[i] else NULL

    .ensure_explorer()

    # Detect entry type and collect one or more DataTrack objects
    new_tracks <- if (grepl("hubUrl=", entry, fixed = TRUE)) {
      # Full UCSC browser URL — extract just the hub URL, use caller's region
      parsed <- if (exists("parse_ucsc_url", mode = "function")) parse_ucsc_url(entry) else NULL
      if (!is.null(parsed) && !is.null(parsed$hub_url) &&
          exists("build_hub_tracks", mode = "function")) {
        build_hub_tracks(parsed$hub_url, chrom, from, to,
                         genome = parsed$genome %||% "hg38")
      } else { message("[WARN] Cannot resolve hub from UCSC URL: ", entry); NULL }

    } else if (grepl("\\.txt(\\?.*)?$", entry, ignore.case = TRUE)) {
      # Direct hub.txt URL — load all bigwig tracks for the region
      if (exists("build_hub_tracks", mode = "function"))
        build_hub_tracks(entry, chrom, from, to)
      else { message("[WARN] build_hub_tracks not available"); NULL }

    } else if (grepl("^https?://|^file://|^/", entry)) {
      # Direct bigwig URL
      tr <- build_bw_track(entry, chrom, from, to,
                           name = label %||% basename(entry))
      list(tr)

    } else {
      # Catalog ID
      if (exists("build_catalog_track", mode = "function")) {
        tr <- build_catalog_track(entry, chrom, from, to)
        if (!is.null(tr) && !is.null(label))
          Gviz::displayPars(tr) <- list(name = label)
        list(tr)
      } else { message("[WARN] build_catalog_track not available"); NULL }
    }

    for (tr in Filter(Negate(is.null), new_tracks %||% list()))
      tracks_out[[length(tracks_out) + 1L]] <- tr
  }
  tracks_out
}

# ── Main plotting function ──────────────────────────────────────────────────────
#' Genome-browser plot for a single MPRA variant.
#'
#' @param chrom          UCSC chromosome, e.g. "chr5"
#' @param pos            0-based position
#' @param ref            Reference allele
#' @param alt            Alternate allele
#' @param rsid           dbSNP rsID — resolves chrom/pos/ref/alt via BioMart
#' @param window         Half-window in bp (default 200 kb)
#' @param outfile        Output PDF path; auto-generated if NULL
#' @param metabrain_dedup  "all_sig" (default), "cortex_EUR", or "best_pvalue"
#'   all_sig:     show all significant eQTLs across all tissues — one arc per gene×tissue
#'   cortex_EUR:  show only cortex_EUR tissue rows — one arc per gene
#'   best_pvalue: show one arc per gene from the most significant tissue
#' @param arc_mode         "split_panel" (default) or "color_only"
#'   split_panel: positive-beta arcs in upper sub-track, negative in lower sub-track
#'   color_only:  all arcs in one track; positive = blue, negative = warm orange
#' @param ucsc_atac      Character vector of ATAC-seq bigwig tracks to add.
#'   Each element is a catalog id (see browse_catalog()) or a direct bigwig URL.
#'   Example: c("boca_glut_dlPFC", "boca_glut_ACC")
#'   Requires source("src/ucsc_atac_explorer.R") for catalog id resolution.
#' @param col_region_sig  Color for MPRA regions with active sequence
#' @param col_var_up      Color for significant activating variants
#' @param col_var_down    Color for significant repressive variants
plot_variant <- function(chrom = NULL, pos = NULL, ref = NULL, alt = NULL,
                          rsid   = NULL,
                          window = 200000L,
                          outfile = NULL,
                          metabrain_dedup = "all_sig",
                          arc_mode        = "split_panel",
                          brain_atac      = NULL,
                          ucsc_atac       = NULL,
                          show_ccres      = TRUE,
                          show_ngn2_atac  = TRUE,
                          show_gtex       = TRUE,
                          show_ems        = TRUE,
                          arc_lwd         = 2.5,
                          col_region_sig  = COL_REGION_SIG,
                          col_var_up      = COL_VAR_SIG_UP,
                          col_var_down    = COL_VAR_SIG_DOWN) {

  if (!is.null(rsid)) {
    coords <- resolve_rsid(rsid)
    chrom  <- coords$chrom; pos <- coords$pos
    ref    <- coords$ref;   alt <- coords$alt
  } else if (is.null(chrom) || is.null(pos) || is.null(ref) || is.null(alt)) {
    stop("Provide either rsid or all of: chrom, pos, ref, alt")
  }

  stopifnot(metabrain_dedup %in% c("all_sig", "cortex_EUR", "best_pvalue"))
  stopifnot(arc_mode %in% c("split_panel", "color_only"))

  genome <- "hg38"
  from   <- pos - window
  to     <- pos + window

  if (is.null(outfile)) {
    name_base <- if (!is.null(rsid)) rsid else sprintf("%s_%d_%s_%s", chrom, pos, ref, alt)
    outfile   <- file.path(OUTPUT_DIR, sprintf("%s_%s_%s.pdf", name_base, metabrain_dedup, arc_mode))
  }
  dir.create(dirname(outfile), showWarnings = FALSE, recursive = TRUE)

  message(sprintf("\nPlotting %s:%d %s>%s  [%d, %d]", chrom, pos, ref, alt, from, to))
  message(sprintf("  metabrain_dedup=%s  arc_mode=%s", metabrain_dedup, arc_mode))

  # ── Load all data ─────────────────────────────────────────────────────────────
  message("  Loading data...")
  mpra_dt     <- load_mpra(chrom, from, to)
  regions_dt  <- load_mpra_regions(chrom, from, to)
  gtex_df     <- if (show_gtex) load_gtex(chrom, pos) else NULL
  meta_df     <- load_metabrain(chrom, pos, metabrain_dedup)
  ems_dt      <- if (show_ems) load_ems(chrom, from, to) else NULL
  ems_arcs_df <- if (show_ems) load_ems_arcs(chrom, pos) else NULL

  # Report MetaBrain eQTL gene targets with p-value and beta (significant rows only)
  meta_genes_df <- if (!is.null(meta_df) && nrow(meta_df) > 0L) {
    d <- as.data.frame(meta_df)
    d <- d[d$is_sig, c("gene_name", "Tissue", "p_val", "beta")]
    d[order(d$gene_name, d$p_val), ]
  } else {
    data.frame(gene_name = character(0), Tissue = character(0),
               p_val = numeric(0), beta = numeric(0))
  }
  if (nrow(meta_genes_df) > 0L) {
    message("  MetaBrain eQTL genes:")
    for (i in seq_len(nrow(meta_genes_df))) {
      r <- meta_genes_df[i, ]
      message(sprintf("    %-12s tissue=%-14s p=%.3g  beta=%.3f",
                      r$gene_name, r$Tissue, r$p_val, r$beta))
    }
  }
  atac_dt    <- load_atac(chrom, from, to)
  ccre_dt    <- if (show_ccres) load_screen_ccres(chrom, from, to) else NULL
  # Local brain ATAC bigwig tracks (GSE113480; built only when brain_atac is set)
  brain_atac_trs <- if (!is.null(brain_atac) && length(brain_atac) > 0L)
    build_brain_atac_tracks(chrom, from, to, which = brain_atac)
  else list()
  # UCSC / external bigwig ATAC tracks (fetched on demand; NULL if ucsc_atac not set)
  ucsc_atac_trs <- if (!is.null(ucsc_atac))
    build_ucsc_atac_tracks(ucsc_atac, chrom, from + 1L, to)
  else list()
  message("  Loading gene models...")
  gene_tr    <- build_gene_track(chrom, from, to, genome)

  # ── Diagnostic summary ────────────────────────────────────────────────────────
  message(sprintf(
    "  MPRA=%s (%s sig) | regions=%s | GTEx=%s (%s sig, %s brain) | Meta=%s (%s sig) | EMS=%s | EMS arcs=%s (%s sig) | ATAC=%s peaks | brain_bw=%s | UCSC_ATAC=%s tracks | gene=%s",
    if (is.null(mpra_dt)) "0" else nrow(mpra_dt),
    if (is.null(mpra_dt)) "0" else sum(mpra_dt$is_sig),
    if (is.null(regions_dt)) "0" else nrow(regions_dt),
    if (is.null(gtex_df)) "0" else nrow(gtex_df),
    if (is.null(gtex_df)) "0" else sum(gtex_df$pip > 0.1, na.rm = TRUE),
    if (is.null(gtex_df)) "0" else sum(gtex_df$is_brain, na.rm = TRUE),
    if (is.null(meta_df)) "0" else nrow(meta_df),
    if (is.null(meta_df)) "0" else sum(meta_df$is_sig, na.rm = TRUE),
    if (is.null(ems_dt))  "0" else nrow(ems_dt),
    if (is.null(ems_arcs_df)) "0" else nrow(ems_arcs_df),
    if (is.null(ems_arcs_df)) "0" else sum(ems_arcs_df$is_sig, na.rm = TRUE),
    if (is.null(atac_dt)) "0" else nrow(atac_dt),
    length(brain_atac_trs),
    length(ucsc_atac_trs),
    if (is.null(gene_tr)) "missing" else "OK"
  ))

  # ── Build tracks (top → bottom) ───────────────────────────────────────────────
  tracks      <- list()
  track_sizes <- numeric(0)

  safe <- function(label, expr) {
    tryCatch(expr, error = function(e) {
      message("  [TRACK FAILED: ", label, "]: ", e$message); NULL
    })
  }

  push <- function(tr_or_list, size = 1) {
    items <- if (is.list(tr_or_list) && !inherits(tr_or_list, "GdObject"))
               tr_or_list else list(tr_or_list)
    for (t in items) {
      if (is.null(t)) next
      tracks[[length(tracks) + 1L]]        <<- t
      track_sizes[length(track_sizes) + 1L] <<- size
    }
  }

  # 1. Genome axis
  push(safe("Axis", GenomeAxisTrack(col = "black")), size = 0.25)

  # 2. Gene models
  if (!is.null(gene_tr)) push(gene_tr, size = 2.0)

  # 3. MPRA tested regions
  if (!is.null(regions_dt))
    push(safe("MPRA Regions",
              build_mpra_region_track(regions_dt, mpra_dt, genome, chrom,
                                      col_sig = col_region_sig)), size = 0.35)

  # 4. MPRA variant effects
  if (!is.null(mpra_dt))
    push(safe("MPRA Variants",
              build_mpra_variant_track(mpra_dt, chrom, genome, target_pos = pos,
                                       col_sig_up   = col_var_up,
                                       col_sig_down = col_var_down)), size = 0.35)

  # 4b. SCREEN cCREs (blue = brain-active, gray = other)
  if (!is.null(ccre_dt))
    push(safe("SCREEN cCREs", build_ccre_track(ccre_dt, genome, chrom)), size = 0.35)

  # 5. GTEx eQTL arcs — 2 tracks: brain (blue) and non-brain (gray), sig only (PIP > 0.1)
  if (!is.null(gtex_df) && nrow(gtex_df) > 0L) {
    gtex_df$is_sig <- gtex_df$pip > 0.1
    arc_tracks <- safe("GTEx arcs",
                       build_eqtl_arc_tracks(gtex_df, "GTEx eQTL", genome, chrom,
                                             arc_mode = "color_only", arc_lwd = arc_lwd))
    push(arc_tracks, size = 0.8)
  }

  # 6. Metabrain eQTL arcs — all brain tissue, so always blue (is_brain = TRUE), sig only
  if (!is.null(meta_df) && nrow(meta_df) > 0L) {
    meta_df_r          <- as.data.frame(meta_df)
    meta_df_r$is_brain <- TRUE
    arc_tracks <- safe("Metabrain arcs",
                       build_eqtl_arc_tracks(meta_df_r, "Metabrain\neQTL", genome, chrom,
                                             arc_mode = "color_only", arc_lwd = arc_lwd))
    push(arc_tracks, size = 0.8)
  }

  # 7. EMS signal (barplot by position)
  if (!is.null(ems_dt))
    push(safe("EMS", build_ems_track(ems_dt, genome, chrom)), size = 0.7)

  # 7b. EMS eQTL arcs (variant → gene TSS)
  if (!is.null(ems_arcs_df) && nrow(ems_arcs_df) > 0L) {
    arc_tracks <- safe("EMS arcs",
                       build_eqtl_arc_tracks(ems_arcs_df, "EMS\neQTL", genome, chrom,
                                             arc_mode = "color_only", arc_lwd = arc_lwd))
    push(arc_tracks, size = 0.8)
  }

  # 8. NGN2 ATAC — filled rectangles showing open chromatin regions
  if (show_ngn2_atac && !is.null(atac_dt))
    push(safe("ATAC", build_atac_track(atac_dt, genome, chrom)), size = 0.5)

  # 9. Brain ATAC-seq bigwig tracks (GSE113480 — astrocyte/cortical/hippocampus/motor)
  for (tr in brain_atac_trs)
    push(safe("Brain ATAC bw", tr), size = 0.5)

  # 10. UCSC / external bigwig ATAC tracks (brain cell types from track hubs)
  for (tr in ucsc_atac_trs)
    push(safe("UCSC ATAC", tr), size = 0.5)

  if (length(tracks) == 0L) {
    message("No tracks produced — check data paths and window size.")
    return(invisible(NULL))
  }

  # ── Wrap all tracks in HighlightTrack at variant position ────────────────────
  highlight_gr <- GRanges(chrom, IRanges(as.integer(pos) + 1L, as.integer(pos) + 1L))
  all_tracks <- HighlightTrack(
    trackList  = tracks,
    range      = highlight_gr,
    col        = COL_HIGHLIGHT,   # border color of the highlight band
    fill       = "#e31a1c18",     # very subtle red fill
    inBackground = TRUE
  )

  message(sprintf("  Track objects: %d | total height: %.1f in",
                  length(tracks), 2 + sum(track_sizes)))

  # ── Render ───────────────────────────────────────────────────────────────────
  pngfile      <- sub("\\.pdf$", ".png", outfile)
  total_height <- 2 + sum(track_sizes)

  do_plot <- function() {
    plotTracks(
      list(all_tracks),
      from             = from,
      to               = to,
      sizes            = track_sizes,
      background.title = "white",
      col.title        = "black",
      fontface.title   = 2,
      cex.title        = 0.8
    )
  }

  message("  Writing PDF → ", outfile)
  pdf(outfile, width = 10, height = total_height)
  tryCatch(do_plot(), error = function(e) { dev.off(); stop("plotTracks (PDF) failed: ", e$message) })
  dev.off()

  message("  Writing PNG → ", pngfile)
  png(pngfile, width = 1200, height = as.integer(total_height * 96), res = 96)
  tryCatch(do_plot(), error = function(e) { dev.off(); stop("plotTracks (PNG) failed: ", e$message) })
  dev.off()

  message("Done: ", outfile, " + ", pngfile)
  invisible(list(outfile = outfile, metabrain_genes = meta_genes_df))
}

# ── Usage reminder ─────────────────────────────────────────────────────────────
message("\n── plot_variants_v3.R loaded ──────────────────────────────────────────────")
message("PREREQUISITE: run preprocessing once before first plot:")
message("  python src/preprocess_eqtl_data.py")
message("")
message("Parameters:")
message("  metabrain_dedup = 'all_sig' (default) | 'cortex_EUR' | 'best_pvalue'")
message("  arc_mode        = 'split_panel' (default) | 'color_only'")
message("  brain_atac      = NULL (default) | subset of c('astrocyte','cortical','hippocampus','motor')")
message("  ucsc_atac       = NULL (default) | character vector of catalog ids or bigwig URLs")
message("")
message("Brain ATAC-seq (UCSC track hubs) — source explorer first:")
message("  source('src/ucsc_atac_explorer.R')")
message("  browse_catalog(excitatory_only = TRUE)          # see curated catalog")
message("  load_atac_hub_tracks('https://ggoma.s3.amazonaws.com/hub_basic.txt')  # inspect hub")
message("")
message("ucsc_atac accepts any mix of:")
message("  UCSC browser URL  — 'http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&hubUrl=https://...'")
message("  hub.txt URL       — 'https://ggoma.s3.amazonaws.com/hub_basic.txt'")
message("  direct bigwig URL — 'https://s3.amazonaws.com/ggoma/hg38/GLU_scaled.bw'")
message("  catalog id        — 'boca_glut_dlPFC'")
message("")
message("Examples:")
message("  plot_variant(rsid = 'rs1257445811')")
message("  plot_variant(rsid = 'rs1257445811', brain_atac = c('astrocyte','cortical','hippocampus','motor'))")
message("  plot_variant(rsid = 'rs1257445811', brain_atac = 'cortical')")
message("  plot_variant(rsid = 'rs1257445811', metabrain_dedup = 'cortex_EUR')
  plot_variant(rsid = 'rs1257445811', metabrain_dedup = 'best_pvalue', arc_mode = 'color_only')")
message("  plot_variant(rsid = 'rs1257445811',")
message("    ucsc_atac = 'http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&hubUrl=https://ggoma.s3.amazonaws.com/hub_basic.txt&position=chr19:35900492-35912218')")
message("  plot_variant(rsid = 'rs1257445811',")
message("    ucsc_atac = c('boca_glut_dlPFC', 'https://s3.amazonaws.com/ggoma/hg38/GLU_scaled.bw'))")
