#!/usr/bin/env python3
"""
Preprocessing script for the 80K MPRA significant variant annotation table.

Generates
---------
data/variant_table/finemapped_eqtl_per_variant_significant.tsv.gz
    Fine-mapped GTEx brain eQTL summary (one row per variant), filtered to the
    ~1018 significant MPRA variants from this study. Only SPDI + eqtl_* columns.

data/variant_table/finemapped_eqtl_full_overlap_significant.tsv.gz
    Full eQTL overlap (one row per variant x tissue x gene association), filtered
    to significant MPRA variants. Only SPDI + eqtl_* columns.

data/variant_table/significant_variants_annotated.tsv.gz
    Main annotation table: all significant variants with selected annotations
    merged with fine-mapped eQTL data. Includes a priority_score column.

Usage
-----
    cd /path/to/variant-browser
    python src/preprocess_variant_table.py

Coordinate note
---------------
SPDI uses 0-based positions (NC_000001.11:pos:REF:ALT). The per-variant and
full-overlap eQTL files were generated by annotate_gtex_eqtl.py, which already
matched SPDIs to 1-based GTEx variant keys — so SPDI is the safe join key here.
"""

from pathlib import Path

import numpy as np
import pandas as pd

# ── Input paths ──────────────────────────────────────────────────────────────────

DATA_BASE = Path("/home/kisa/coding")

VARIANT_INFO = DATA_BASE / (
    "80K_MPRA/80K-Analysis/09_mpra_manuscript/results/variant_info/"
    "2602_variant_info_significant_annot_with_predictions.tsv.gz"
)
EQTL_PER_VARIANT = DATA_BASE / (
    "IAWG_IGVF/data/neuron_variant/2605_finemapped_eQTLs/2606_finemapped_eQTL/"
    "gtex_brain_eqtl_per_variant.tsv.gz"
)
EQTL_FULL_OVERLAP = DATA_BASE / (
    "IAWG_IGVF/data/neuron_variant/2605_finemapped_eQTLs/2606_finemapped_eQTL/"
    "gtex_brain_eqtl_full_overlap.tsv.gz"
)

OUT_DIR = Path("data/variant_table")

MANUSCRIPT_VARIANTS = {"rs11635753", "rs1257445811", "rs11789013", "rs1128287"}

# ── Column selection for the annotation table ────────────────────────────────────
# Columns from 2602_variant_info_significant_annot_with_predictions.tsv.gz to keep.
# The fine-mapped eQTL columns (eqtl_*) are merged in separately from the eQTL files.

KEEP_COLS = [
    # Identity
    "ID", "rsid", "SPDI", "chr", "variant_pos", "REF", "ALT",
    "gnomad_AF", "gnomad_AF_popmax", "af_category",
    # MPRA variant-level allelic effect
    "NGN2_variant_logFC", "NGN2_variant_adj_p-value", "NGN2_variant_is_significant",
    # Region-level activity
    "NGN2_region_logFC", "NGN2_region_adj_p-value", "significant_region_NGN2",
    "NGN2_region_normalized_activity", "reference_activity_category", "variant_effect_category",
    # Chromatin / accessibility
    "DNase_max", "enformer_class",
    "is_ngn2_atac_overlap", "is_open_chromatin_ngn2_single_cell", "is_brain_SCREEN_cCRE",
    # TF binding
    "has_tfbs_overlap", "has_TFBS_diff_in_affinity",
    "local_bitscore_tf_gene_symbol", "local_bitscore_delta_local_bit_score",
    "REMAP2022_n_unique_TFBS",
    # GWAS catalog (no significance threshold; includes all catalog entries)
    "has_any_GWAS_overlap", "has_brain_GWAS_trait",
    "GWAS_DISEASE_TRAIT", "GWAS_PVALUE_min", "direct_GWAS_hit",
    # Enhancer-to-gene links (brain)
    "brain_any_e2g", "brain_strong_e2g", "brain_very_strong_e2g",
    "brain_e2g_gene_name", "brain_e2g_score_max", "brain_e2g_distance_to_TSS",
    # Enhancer-to-gene links (cardiac, for comparison)
    "cardiac_any_e2g", "cardiac_strong_e2g", "cardiac_e2g_gene_name",
    # EMS (Enhancer–Modulator Score, brain tissues)
    "overlaps_EMS_brain", "EMS_brain_genes", "EMS_brain_n_tissues",
    # Non-finemapped GTEx (all tissues, included in variant info table)
    "has_gtex_overlap", "GTEx_high_confidence_eQTL",
    "GTEx_brain_tissue", "GTEx_brain_high_confidence",
    "GTEx_pip_max", "GTEx_gene_symbols", "GTEx_tissues",
    # Closest gene (distance-based)
    "closest_tss_gene_name", "minimal_tss_distance_associated_gene",
    # UKBB fine-mapped traits
    "has_any_UKBB_overlap", "has_conf_UKBB_overlap", "UKBB_trait_descriptions",
    # Conservation / constraint
    "phastCons_mean", "CADD17_PHRED",
    # AI/sequence model predictions
    "well_predicted", "alphaGe_global_mean_abs",
    # Study context
    "multi_region", "multi_variant_region", "n_additional_sources",
    "interpretation_summary",
]

# eQTL summary columns to merge from the per-variant file
EQTL_MERGE_COLS = [
    "SPDI",
    "eqtl_max_pip",
    "eqtl_best_pip_gene_symbol", "eqtl_best_pip_tissue",
    "eqtl_best_pip_beta_marginal", "eqtl_best_pip_beta_posterior",
    "eqtl_best_pip_z", "eqtl_best_pip_cs_id", "eqtl_best_pip_maf",
    "eqtl_ivw_beta_marginal",
    "eqtl_n_brain_associations", "eqtl_n_brain_genes", "eqtl_n_brain_tissues",
    "eqtl_gene_symbol_list", "eqtl_gene_id_list", "eqtl_tissue_list",
    "eqtl_is_brain_eqtl_pip001", "eqtl_is_brain_eqtl_pip01",
    "eqtl_is_brain_eqtl_pip05", "eqtl_is_brain_eqtl_pip09",
]


# ── Priority scoring ─────────────────────────────────────────────────────────────

def _bool_col(df: pd.DataFrame, col: str) -> pd.Series:
    """Return a boolean Series for a column, defaulting to False if absent."""
    if col not in df.columns:
        return pd.Series(False, index=df.index)
    return df[col].fillna(False).astype(bool)


def compute_priority_score(df: pd.DataFrame) -> pd.Series:
    """
    Composite priority score for ranking variants as interesting examples.

    Tiers (additive):
      Fine-mapped eQTL PIP ≥ 0.9  → +5   (very high confidence causal eQTL)
      Fine-mapped eQTL PIP ≥ 0.5  → +4
      Fine-mapped eQTL PIP ≥ 0.1  → +3
      Fine-mapped eQTL PIP ≥ 0.01 → +1
      Brain GWAS trait             → +3
      Any GWAS (non-brain)         → +1
      Very strong brain E2G        → +3
      Strong brain E2G             → +2
      Any brain E2G                → +1
      TFBS disruption (diff affin) → +2
      Any TFBS overlap             → +1
      |logFC| ≥ 1.5                → +2
      |logFC| ≥ 1.0                → +1
      phastCons > 0.5              → +1
    """
    score = pd.Series(0.0, index=df.index)

    pip = pd.to_numeric(df.get("eqtl_max_pip"), errors="coerce")
    score += np.select(
        [pip >= 0.9, pip >= 0.5, pip >= 0.1, pip >= 0.01],
        [5,          4,          3,          1],
        default=0,
    )

    has_brain_gwas = _bool_col(df, "has_brain_GWAS_trait")
    has_any_gwas   = _bool_col(df, "has_any_GWAS_overlap")
    score += has_brain_gwas.astype(int) * 3
    score += (has_any_gwas & ~has_brain_gwas).astype(int)

    very_strong_e2g = _bool_col(df, "brain_very_strong_e2g")
    strong_e2g      = _bool_col(df, "brain_strong_e2g")
    any_e2g         = _bool_col(df, "brain_any_e2g")
    score += very_strong_e2g.astype(int) * 3
    score += (strong_e2g & ~very_strong_e2g).astype(int) * 2
    score += (any_e2g & ~strong_e2g).astype(int)

    has_tfbs_diff = _bool_col(df, "has_TFBS_diff_in_affinity")
    has_tfbs_any  = _bool_col(df, "has_tfbs_overlap")
    score += has_tfbs_diff.astype(int) * 2
    score += (has_tfbs_any & ~has_tfbs_diff).astype(int)

    logfc_abs = pd.to_numeric(df.get("NGN2_variant_logFC"), errors="coerce").abs()
    score += np.where(logfc_abs >= 1.5, 2, np.where(logfc_abs >= 1.0, 1, 0))

    phastcons = pd.to_numeric(df.get("phastCons_mean"), errors="coerce").fillna(0)
    score += (phastcons > 0.5).astype(int)

    return score.astype(int)


# ── Main ─────────────────────────────────────────────────────────────────────────

def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # ── 1. Load significant variant table ────────────────────────────────────────
    print(f"Loading significant variant info:\n  {VARIANT_INFO}")
    sig_df = pd.read_csv(VARIANT_INFO, sep="\t", low_memory=False)
    n_total = len(sig_df)
    print(f"  {n_total:,} variants | {sig_df['SPDI'].nunique():,} unique SPDIs")

    sig_spdis = set(sig_df["SPDI"].dropna())

    # ── 2. Filter and clean per-variant eQTL summary ─────────────────────────────
    print(f"\nLoading per-variant eQTL file:\n  {EQTL_PER_VARIANT}")
    eqtl_pv = pd.read_csv(EQTL_PER_VARIANT, sep="\t", low_memory=False)
    print(f"  {len(eqtl_pv):,} rows | {eqtl_pv['SPDI'].nunique():,} unique SPDIs (all MPRA studies)")

    eqtl_pv_sig = eqtl_pv[eqtl_pv["SPDI"].isin(sig_spdis)].copy()
    print(f"  After filtering to this study's significant variants: {len(eqtl_pv_sig):,} rows")

    # Keep only SPDI + eqtl_* columns (drop other MPRA study columns)
    eqtl_only_cols = ["SPDI"] + [c for c in eqtl_pv_sig.columns if c.startswith("eqtl_")]
    eqtl_pv_sig = eqtl_pv_sig[eqtl_only_cols].reset_index(drop=True)

    out_pv = OUT_DIR / "finemapped_eqtl_per_variant_significant.tsv.gz"
    eqtl_pv_sig.to_csv(out_pv, sep="\t", index=False, compression="gzip")
    print(f"  Written: {out_pv}")

    # ── 3. Filter and clean full eQTL overlap ────────────────────────────────────
    print(f"\nLoading full eQTL overlap file:\n  {EQTL_FULL_OVERLAP}")
    eqtl_full = pd.read_csv(EQTL_FULL_OVERLAP, sep="\t", low_memory=False)
    print(f"  {len(eqtl_full):,} rows (variant × tissue × gene associations)")

    eqtl_full_sig = eqtl_full[eqtl_full["SPDI"].isin(sig_spdis)].copy()
    print(f"  After filtering: {len(eqtl_full_sig):,} rows | {eqtl_full_sig['SPDI'].nunique():,} unique SPDIs")

    eqtl_full_only_cols = ["SPDI"] + [c for c in eqtl_full_sig.columns if c.startswith("eqtl_")]
    eqtl_full_sig = eqtl_full_sig[eqtl_full_only_cols].reset_index(drop=True)

    out_full = OUT_DIR / "finemapped_eqtl_full_overlap_significant.tsv.gz"
    eqtl_full_sig.to_csv(out_full, sep="\t", index=False, compression="gzip")
    print(f"  Written: {out_full}")

    # ── 4. Build annotation table ─────────────────────────────────────────────────
    print("\nBuilding annotation table...")

    # Select columns that exist; warn about any missing
    keep_existing = [c for c in KEEP_COLS if c in sig_df.columns]
    missing = set(KEEP_COLS) - set(sig_df.columns)
    if missing:
        print(f"  Note: {len(missing)} requested columns absent from variant info (skipped):")
        for c in sorted(missing):
            print(f"    {c}")

    annot = sig_df[keep_existing].copy()

    # Merge fine-mapped eQTL summary (left join — keeps all significant variants)
    merge_cols = [c for c in EQTL_MERGE_COLS if c in eqtl_pv_sig.columns]
    annot = annot.merge(eqtl_pv_sig[merge_cols], on="SPDI", how="left")

    # Cast boolean pip-threshold flags (stored as object in TSV)
    for col in ["eqtl_is_brain_eqtl_pip001", "eqtl_is_brain_eqtl_pip01",
                "eqtl_is_brain_eqtl_pip05", "eqtl_is_brain_eqtl_pip09"]:
        if col in annot.columns:
            annot[col] = annot[col].fillna(False).astype(bool)

    annot["priority_score"] = compute_priority_score(annot)
    annot["in_manuscript"]  = annot["rsid"].isin(MANUSCRIPT_VARIANTS)

    out_annot = OUT_DIR / "significant_variants_annotated.tsv.gz"
    annot.to_csv(out_annot, sep="\t", index=False, compression="gzip")
    print(f"  Written: {out_annot}  ({annot.shape[0]} rows × {annot.shape[1]} columns)")

    # ── 5. Summary statistics ─────────────────────────────────────────────────────
    print("\n" + "═" * 70)
    print("SUMMARY STATISTICS")
    print("═" * 70)
    print(f"Total significant MPRA variants: {n_total:,}")

    # Fine-mapped eQTL
    has_any_eqtl = annot["eqtl_max_pip"].notna()
    print(f"\nFine-mapped GTEx brain eQTL overlap:")
    print(f"  Any association (PIP > 0):  {has_any_eqtl.sum():4d}  ({100*has_any_eqtl.mean():.1f}%)")
    # Fine-mapped eQTL: per-threshold counts + rsids if small group
    for col, label in [
        ("eqtl_is_brain_eqtl_pip001", "PIP ≥ 0.01"),
        ("eqtl_is_brain_eqtl_pip01",  "PIP ≥ 0.10"),
        ("eqtl_is_brain_eqtl_pip05",  "PIP ≥ 0.50"),
        ("eqtl_is_brain_eqtl_pip09",  "PIP ≥ 0.90"),
    ]:
        if col in annot.columns:
            rows_hit = annot[annot[col].fillna(False)]
            n = len(rows_hit)
            rsid_str = ""
            if n < 10:
                rsids_hit = rows_hit["rsid"].dropna().tolist()
                genes_hit = rows_hit["eqtl_best_pip_gene_symbol"].apply(
                    lambda v: str(v) if pd.notna(v) else "?"
                ).tolist()
                rsid_str = "  → " + ", ".join(
                    f"{r}({g})" for r, g in zip(rsids_hit, genes_hit)
                )
            print(f"  {label}:           {n:4d}  ({100*n/n_total:.1f}%){rsid_str}")

    # Unique genes at PIP ≥ 0.1
    if "eqtl_is_brain_eqtl_pip01" in annot.columns:
        pip01_rows = annot[annot["eqtl_is_brain_eqtl_pip01"].fillna(False)]
        genes_pip01 = {
            g.strip()
            for gl in pip01_rows["eqtl_gene_symbol_list"].dropna()
            for g in str(gl).split(";")
            if g.strip() and g.strip() != "nan"
        }
        print(f"\n  Unique target genes at PIP ≥ 0.10: {len(genes_pip01)}")
        if genes_pip01:
            print(f"  {', '.join(sorted(genes_pip01))}")

    # Non-finemapped GTEx (for comparison)
    if "has_gtex_overlap" in annot.columns:
        n_gtex = _bool_col(annot, "has_gtex_overlap").sum()
        gtex_brain_rows = annot[_bool_col(annot, "GTEx_brain_high_confidence")]
        n_gtex_brain = len(gtex_brain_rows)
        print(f"\nNon-finemapped GTEx (variant info table):")
        print(f"  Any GTEx eQTL:             {n_gtex:4d}  ({100*n_gtex/n_total:.1f}%)")
        brain_rsid_str = ""
        if n_gtex_brain < 10:
            brain_rsids = gtex_brain_rows["rsid"].dropna().tolist()
            brain_genes = gtex_brain_rows["GTEx_gene_symbols"].apply(
                lambda v: str(v) if pd.notna(v) else "?"
            ).tolist()
            brain_rsid_str = "  → " + ", ".join(
                f"{r}({g})" for r, g in zip(brain_rsids, brain_genes)
            )
        print(f"  Brain high-confidence:     {n_gtex_brain:4d}  ({100*n_gtex_brain/n_total:.1f}%){brain_rsid_str}")

    # GWAS
    # Note: has_brain_GWAS_trait is pre-computed in the upstream variant info table.
    # It captures neurological/psychiatric/behavioral traits (e.g. insomnia, educational
    # attainment, essential tremor, smoking) but also some broader traits (height, weight).
    # Inspect GWAS_DISEASE_TRAIT column for the actual trait labels per variant.
    n_gwas_any   = _bool_col(annot, "has_any_GWAS_overlap").sum()
    gwas_brain_rows = annot[_bool_col(annot, "has_brain_GWAS_trait")]
    n_gwas_brain = len(gwas_brain_rows)
    print(f"\nGWAS catalog overlap (no significance threshold applied):")
    print(f"  Any GWAS hit:              {n_gwas_any:4d}  ({100*n_gwas_any/n_total:.1f}%)")
    gwas_rsid_str = ""
    if n_gwas_brain < 10:
        gwas_rsids  = gwas_brain_rows["rsid"].dropna().tolist()
        gwas_traits = gwas_brain_rows["GWAS_DISEASE_TRAIT"].apply(
            lambda v: str(v)[:40] if pd.notna(v) else "?"
        ).tolist()
        gwas_rsid_str = "\n" + "\n".join(
            f"    {r}: {t}" for r, t in zip(gwas_rsids, gwas_traits)
        )
    print(f"  Brain/psych trait:         {n_gwas_brain:4d}  ({100*n_gwas_brain/n_total:.1f}%){gwas_rsid_str}")

    # E2G
    n_e2g_any   = _bool_col(annot, "brain_any_e2g").sum()
    n_e2g_str   = _bool_col(annot, "brain_strong_e2g").sum()
    n_e2g_vstr  = _bool_col(annot, "brain_very_strong_e2g").sum()
    print(f"\nBrain enhancer-to-gene (E2G) links:")
    print(f"  Any E2G:                   {n_e2g_any:4d}  ({100*n_e2g_any/n_total:.1f}%)")
    print(f"  Strong E2G:                {n_e2g_str:4d}  ({100*n_e2g_str/n_total:.1f}%)")
    print(f"  Very strong E2G:           {n_e2g_vstr:4d}  ({100*n_e2g_vstr/n_total:.1f}%)")

    # UKBB
    n_ukbb = _bool_col(annot, "has_conf_UKBB_overlap").sum()
    print(f"\nUKBB fine-mapped trait overlap (high-confidence): {n_ukbb}")

    # Manuscript variants
    print(f"\n{'─'*70}")
    print("Manuscript variants:")
    ms_df = annot[annot["in_manuscript"]].sort_values("rsid")
    for _, row in ms_df.iterrows():
        pip     = row.get("eqtl_max_pip")
        pip_str = f"PIP={pip:.3f}" if pd.notna(pip) else "no fine-mapped eQTL"
        gene    = str(row.get("eqtl_best_pip_gene_symbol")) if pd.notna(row.get("eqtl_best_pip_gene_symbol")) else "—"
        tissue_val = row.get("eqtl_best_pip_tissue")
        tissue  = str(tissue_val).replace("Brain_", "") if pd.notna(tissue_val) else "—"
        logfc   = row.get("NGN2_variant_logFC", float("nan"))
        print(f"  {row['rsid']:<20s}  logFC={logfc:+.3f}  {pip_str}  gene={gene}  tissue={tissue}")

    # Top candidates by priority score (excluding already-selected manuscript variants)
    print(f"\n{'─'*70}")
    print("Top 25 candidate variants by priority score (excl. manuscript variants):")
    print(f"  {'score':>5}  {'rsid':<22}  {'logFC':>7}  {'eQTL PIP':>9}  {'eQTL gene':<18}  {'E2G gene':<18}  flags")
    top = (
        annot[~annot["in_manuscript"]]
        .sort_values(["priority_score", "eqtl_max_pip"], ascending=[False, False])
        .head(25)
    )
    for _, row in top.iterrows():
        pip      = row.get("eqtl_max_pip")
        pip_str  = f"{pip:.3f}" if pd.notna(pip) else "   —   "
        gene     = str(row.get("eqtl_best_pip_gene_symbol")) if pd.notna(row.get("eqtl_best_pip_gene_symbol")) else "—"
        e2g_gene = str(row.get("brain_e2g_gene_name")) if pd.notna(row.get("brain_e2g_gene_name")) else "—"
        logfc    = row.get("NGN2_variant_logFC", float("nan"))
        rsid     = row.get("rsid") or row.get("ID", "?")
        flags    = " ".join(filter(None, [
            "GWAS"  if row.get("has_brain_GWAS_trait") else "",
            "E2G"   if row.get("brain_strong_e2g")     else "",
            "TFBS"  if row.get("has_TFBS_diff_in_affinity") else "",
            "UKBB"  if row.get("has_conf_UKBB_overlap") else "",
        ]))
        print(
            f"  {int(row['priority_score']):>5}  {rsid:<22}  {logfc:>+7.3f}"
            f"  {pip_str:>9}  {gene:<18}  {e2g_gene:<18}  {flags}"
        )

    print(f"\n{'═'*70}")
    print("Suggested sorting strategy for example selection:")
    print("  1. High fine-mapped PIP (≥0.5): strong causal eQTL in brain tissue")
    print("  2. Brain GWAS overlap: links variant to neuropsychiatric phenotype")
    print("  3. Convergent evidence (E2G + eQTL pointing to same gene)")
    print("  4. TFBS disruption: mechanistic hypothesis for regulatory effect")
    print("  Effect size (|logFC|) as tie-breaker within each tier")
    print(f"\nOutput files written to: {OUT_DIR.resolve()}/")


if __name__ == "__main__":
    main()
